### ISSUE TITLE
Unknown command error 

### ISSUE THREAD

**Issue by XufengXufengXufeng** [RedisLabs/redisgraph-py#24]
OS: Ubuntu 16
python: 3.6
redis: 2.8.19

I am new to redis graph. I don't know where else I can find help.

I followed the Example: Using the Python Client on the title page of this repo. I can't get anything running. Every command, "graph.delete", "graph.commit", "graph.query", are unknown. If anyone, please help.

Thank you.

**Comment by swilly22** [comment]
@XufengXufengXufeng seems like you haven't loaded redisgraph to Redis,

Please try running redisgraph using docker:
`docker run -p 6379:6379 -it --rm redislabs/redisgraph`

Then connect to it using redisgraph-py

**Comment by Glitchfix** [comment]
You could either use the solution mentoined by @swilly22 or load the module directly to make it work
```sh
~/$ redis-server --loadmodule /path/to/module/src/redisgraph.so
```

**Comment by XufengXufengXufeng** [comment]
Thank you @Glitchfix @swilly22 , I can't use docker right now. While I have tried:

~/$ redis-server --loadmodule /path/to/module/src/redisgraph.so

I got the "Bad directive or wrong number of arguments" error. I am sure my path was correct, as I could cd and vim the path without any problem. 

Do you guys know the fix to this redis problem?

Thank you.

**Comment by XufengXufengXufeng** [comment]
I am so sorry, there was a typo or something. It works now. 

Although I tried to add one line to the "loadmodule /path/to/module/src/redsigraph.so" to redis.conf file, it didnot load the module like what I imagined.

**Comment by Glitchfix** [comment]
@XufengXufengXufeng are you able to query now?
